# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
java_version=25
neo_form_version=26.1.2-1

fabric_version=0.19.2
fabric_api_version=0.150.0+26.1.2
neo_version=26.1.2.71
neo_version_range=[26.1.2.71,)

# Mod Properties
mod_id=examplemod
mod_name=Example Mod
mod_license=ARR
mod_version=1.0
group=com.example.examplemod
mod_authors=Mod authors
description=Mod description
